### ISSUE TITLE
Versions?

### ISSUE THREAD

**Issue by ewebgh33** [limitbreakinc/creator-token-standards#16]
v1 or v2?
If v2, why not deprecate v1 and move them out. Is v2 the recommended way to proceed?

Please see
https://github.com/limitbreakinc/creator-token-contracts/issues/12

Can you give some detail on what the v2's improve, beyond the brief, points in the release notes md.
Thanks!

**Comment by ewebgh33** [comment]
Ping
It's quiet in here

**Comment by ewebgh33** [comment]
Bueller

**Comment by nathanglb** [comment]
Yes, the recommendation is to use V2 going forward.  We left both versions present temporarily during the transition period and this will be cleaned up.

**Comment by ewebgh33** [comment]
Does the issue closed mean it is cleaned up already?

**Comment by nathanglb** [comment]
It is cleaned up in the V3 audit branch, which will be merged upon conclusion of audit.

https://github.com/limitbreakinc/creator-token-standards/tree/audit-v3
