### ISSUE TITLE
Transfer Disabled Level (Soul bound)

### ISSUE THREAD

**Issue by ScreamingHawk** [limitbreakinc/creator-token-standards#24]
I recently submitted a PR to the other creator-token repo, adding a new security level that blocks transfers entirely. 
This effectively makes tokens "soul bound" while in this state. 

https://github.com/limitbreakinc/creator-token-contracts/pull/13

I'm interested in adding a PR to this repo to introduce the same change. 
Would it be best to add as a v3? Or to append to the existing v2 implementation?

**Comment by nathanglb** [comment]
We actually just did this in creator-token-standards v3.0.0.  The code is available now, and the transfer validator that support soulbound mode has been deployed already.

**Comment by nathanglb** [comment]
https://github.com/limitbreakinc/creator-token-standards/blob/main/src/utils/CreatorTokenTransferValidator.sol#L303-L337

**Comment by nathanglb** [comment]
https://github.com/limitbreakinc/creator-token-standards/blob/main/src/utils/CreatorTokenTransferValidator.sol#L1778-L1780

**Comment by nathanglb** [comment]
This has been added to the official V3 release.
