### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by fallanic** [limitbreakinc/creator-token-standards#32]
Hi there!

It seems like v3 is production ready (there is a section in the [documentation website](https://erc721c.com/docs/category/for-creators-1) and a [tag on GitHub from May 24th](https://github.com/limitbreakinc/creator-token-standards/releases/tag/v3.0.0))?
So we were wondering if a new npm package will be published soon?
Or would you recommend sticking to the v2 for now?

Thanks a lot in advance, and kudos on the great work!

**Comment by nathanglb** [comment]
Thanks for the callout - yes, we will work on officially releasing the V3 npm package ASAP.  A forge dependency was added to the Limit Break PermitC repository, so in order to build the v3 npm package we must first create a PermitC npm package so that we can build using hardhat.  Coming soon.

**Comment by nathanglb** [comment]
Published v3.0.0 to NPM.

https://www.npmjs.com/package/@limitbreak/creator-token-standards

The package has a dependency on the new permit-c npm package.

https://www.npmjs.com/package/@limitbreak/permit-c
